DROP TRIGGER TRIGGER_DISCARD_SUM_ON_ORDER_PLACE ON ORDERS;

DROP FUNCTION DISCARD_SUM_ON_ORDER_PLACE;

DROP TRIGGER TRIGGER_UPDATE_SUM_ON_ORDER_COMPLETION ON ORDERS;

DROP FUNCTION UPDATE_SUM_ON_ORDER_COMPLETION;

DROP TRIGGER TRIGGER_UPDATE_MATERIALS ON ORDERS;

DROP FUNCTION UPDATE_MATERIALS;

DROP FUNCTION USER_MONEY_DISMISSAL;

DROP FUNCTION USER_MONEY_REPLENISHMENT;

DROP FUNCTION FINAL_COST;

CREATE OR REPLACE FUNCTION DISCARD_SUM_ON_ORDER_PLACE () RETURNS TRIGGER AS $$
BEGIN

	IF (SELECT MONEY - FINAL_COST(NEW.ID) FROM ACCOUNT WHERE LOGIN = (SELECT CUSTOMER FROM ORDERS_LIST WHERE ID = NEW.ID)) < 0 THEN
		RAISE EXCEPTION 'Not enough money to proceed operation';
	END IF;
	
	UPDATE ACCOUNT
	SET MONEY = MONEY - FINAL_COST(NEW.ID)
	WHERE LOGIN = (
		SELECT CUSTOMER 
		FROM ORDERS_LIST
		WHERE ID = NEW.ID
	);
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE TRIGGER TRIGGER_DISCARD_SUM_ON_ORDER_PLACE BEFORE INSERT ON ORDERS FOR EACH ROW
EXECUTE FUNCTION DISCARD_SUM_ON_ORDER_PLACE ();

CREATE OR REPLACE FUNCTION UPDATE_SUM_ON_ORDER_COMPLETION () RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.STATUS = 'Завершен') THEN
		UPDATE ACCOUNT
		SET MONEY = MONEY + FINAL_COST(NEW.ID) * M.WAGE FROM MASTER
		WHERE LOGIN = (
			SELECT MASTER 
			FROM ORDERS_LIST 
			WHERE ID = NEW.ID
		);
	END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE TRIGGER TRIGGER_UPDATE_SUM_ON_ORDER_COMPLETION
AFTER
UPDATE ON ORDERS FOR EACH ROW
EXECUTE FUNCTION UPDATE_SUM_ON_ORDER_COMPLETION ();

CREATE OR REPLACE FUNCTION UPDATE_MATERIALS () RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.STATUS = 'Завершен') THEN
		UPDATE MATERIALS
		SET AMOUNT = AMOUNT - MIOT1.AVERAGE_AMOUNT_USED FROM MATERIALS_IN_ORDER_TYPE AS MIOT1
		WHERE NAME IN (
			SELECT MIOT2.MATERIAL_NAME FROM MATERIALS_IN_ORDER_TYPE AS MIOT2
			WHERE MIOT2.ORDER_TYPE_NAME IN (
				SELECT OTIO.NAME FROM ORDER_TYPES_IN_ORDERS AS OTIO
				WHERE OTIO.ID = NEW.ID
			)
		);
		UPDATE MATERIALS
		SET AMOUNT = 0
		WHERE AMOUNT < 0;
	END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE TRIGGER TRIGGER_UPDATE_MATERIALS
AFTER
UPDATE ON ORDERS FOR EACH ROW
EXECUTE FUNCTION UPDATE_MATERIALS ();

CREATE OR REPLACE FUNCTION USER_MONEY_REPLENISHMENT (
	ACCOUNTLOGIN VARCHAR(32),
	REPLENSHMENT_AMOUNT REAL
) RETURNS VOID AS $$
BEGIN
    INSERT INTO TRANSACTIONS (ACCOUNT, TRANSACTION_SUM, WHAT_TRANSACTION, TIMESTAMP)
    VALUES (ACCOUNTLOGIN, REPLENSHMENT_AMOUNT, 'Пополнение', CURRENT_TIMESTAMP);

	UPDATE ACCOUNT
	SET MONEY = MONEY + REPLENSHMENT_AMOUNT
	WHERE LOGIN = ACCOUNTLOGIN;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE OR REPLACE FUNCTION USER_MONEY_DISMISSAL (ACCOUNTLOGIN VARCHAR(32), DISMISSAL_AMOUNT REAL) RETURNS VOID AS $$
BEGIN
    INSERT INTO TRANSACTIONS (ACCOUNT, TRANSACTION_SUM, WHAT_TRANSACTION, TIMESTAMP)
    VALUES (ACCOUNTLOGIN, DISMISSAL_AMOUNT, 'Списание', CURRENT_TIMESTAMP);

	IF (SELECT MONEY - DISMISSAL_AMOUNT FROM ACCOUNT WHERE LOGIN = ACCOUNTLOGIN) < 0 THEN
		INSERT INTO TRANSACTIONS (
        ACCOUNT,
        TRANSACTION_SUM,
        WHAT_TRANSACTION,
		TIMESTAMP) 
		VALUES (
        ACCOUNTLOGIN,
		DISMISSAL_AMOUNT,
        'Отклонено',
		CURRENT_TIMESTAMP);
	ELSE
		UPDATE ACCOUNT
		SET MONEY = MONEY - DISMISSAL_AMOUNT
		WHERE LOGIN = ACCOUNTLOGIN;
	END IF;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE OR REPLACE FUNCTION FINAL_COST (ORDERID INTEGER) RETURNS REAL AS $$
DECLARE
	_COST REAL;
BEGIN
    SELECT SUM(MIOT.AVERAGE_AMOUNT_USED * M.COST) INTO _COST FROM MATERIALS AS M	 				
	JOIN MATERIALS_IN_ORDER_TYPE AS MIOT ON MIOT.MATERIAL_NAME = M.NAME	
	WHERE MIOT.ORDER_TYPE_NAME IN (							
		SELECT NAME FROM ORDER_TYPES_IN_ORDERS 		
		WHERE ID = ORDERID								
	);
	RETURN _COST;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;