CREATE ROLE ACCOUNTED_USER LOGIN PASSWORD 'QWERTY';
GRANT SELECT ON ORDERS_LIST, ORDER_TYPE, MATERIALS, MATERIALS_IN_ORDER_TYPE, MASTER TO ACCOUNTED_USER;
GRANT SELECT, INSERT ON ORDERS, TRANSACTIONS, ORDER_TYPES_IN_ORDERS TO ACCOUNTED_USER;
GRANT SELECT, UPDATE ON ACCOUNT TO ACCOUNTED_USER;
GRANT EXECUTE ON FUNCTION 
USER_MONEY_REPLENISHMENT (ACCOUNTLOGIN VARCHAR(32), REPLENSHMENT_AMOUNT REAL),
USER_MONEY_DISMISSAL (ACCOUNTLOGIN VARCHAR(32), DISMISSAL_AMOUNT REAL),
FINAL_COST (ORDERID INTEGER)
TO ACCOUNTED_USER;

CREATE ROLE WORKER LOGIN PASSWORD '09876';
GRANT SELECT ON ORDERS_LIST, ORDER_TYPE, MATERIALS, MATERIALS_IN_ORDER_TYPE, MASTER TO WORKER;
GRANT SELECT, INSERT ON TRANSACTIONS, ORDER_TYPES_IN_ORDERS TO WORKER;
GRANT SELECT, UPDATE ON ORDERS, ACCOUNT TO WORKER;
GRANT EXECUTE ON FUNCTION 
USER_MONEY_REPLENISHMENT (ACCOUNTLOGIN VARCHAR(32), REPLENSHMENT_AMOUNT REAL),
USER_MONEY_DISMISSAL (ACCOUNTLOGIN VARCHAR(32), DISMISSAL_AMOUNT REAL),
FINAL_COST (ORDERID INTEGER)
TO WORKER;

CREATE ROLE ADMINISTRATOR LOGIN PASSWORD '12345';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO ADMINISTRATOR;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT ALL ON TABLES TO ADMINISTRATOR;