-- INSERT INTO ORDERS(CONTRACT_URL, STATUS, CUSTOMER, MASTER) VALUES ('contracts/order21.pdf', 'В обработке', 'user2', 'master1');
-- INSERT INTO ORDER_TYPES_IN_ORDERS(ID, NAME) VALUES(21, 'Реставрация фото'), (21, 'Ретушь');
UPDATE ORDERS SET STATUS = 'Размещён' WHERE ID = 21;
-- SELECT * FROM ACCOUNT WHERE LOGIN = 'user2';
-- SELECT USER_MONEY_DISMISSAL('user2', 7921);
-- SELECT FINAL_COST
SELECT * FROM ORDERS;
-- SELECT FINAL_COST(2)