DROP TRIGGER IF EXISTS TRIGGER_DISCARD_SUM_ON_ORDER_PLACE ON ORDERS;

DROP FUNCTION IF EXISTS DISCARD_SUM_ON_ORDER_PLACE;

DROP TRIGGER IF EXISTS TRIGGER_UPDATE_SUM_ON_ORDER_COMPLETION ON ORDERS;

DROP FUNCTION IF EXISTS UPDATE_SUM_ON_ORDER_COMPLETION;

DROP TRIGGER IF EXISTS TRIGGER_UPDATE_MATERIALS ON ORDERS;

DROP FUNCTION IF EXISTS UPDATE_MATERIALS;

DROP FUNCTION IF EXISTS USER_MONEY_DISMISSAL;

DROP FUNCTION IF EXISTS USER_MONEY_REPLENISHMENT;

DROP FUNCTION IF EXISTS FINAL_COST;

DROP FUNCTION IF EXISTS GET_ALL_TYPES;

CREATE OR REPLACE FUNCTION DISCARD_SUM_ON_ORDER_PLACE () RETURNS TRIGGER AS $$
BEGIN
	IF (NEW.STATUS = 'Размещён') THEN
		IF (SELECT MONEY FROM ACCOUNT WHERE LOGIN = NEW.CUSTOMER) < FINAL_COST(NEW.ID) THEN
			NEW.STATUS = 'Отклонён';
		ELSE
			UPDATE ACCOUNT
			SET MONEY = MONEY - FINAL_COST(NEW.ID)
			WHERE LOGIN = NEW.CUSTOMER;
		END IF;
	END IF;
	RETURN NEW;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE TRIGGER TRIGGER_DISCARD_SUM_ON_ORDER_PLACE BEFORE UPDATE ON ORDERS FOR EACH ROW
EXECUTE FUNCTION DISCARD_SUM_ON_ORDER_PLACE ();

CREATE OR REPLACE FUNCTION UPDATE_SUM_ON_ORDER_COMPLETION () RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.STATUS = 'Завершен') THEN
		UPDATE ACCOUNT
		SET MONEY = MONEY + FINAL_COST(NEW.ID) * M.WAGE FROM MASTER AS M
		WHERE LOGIN = NEW.CUSTOMER;
	END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE TRIGGER TRIGGER_UPDATE_SUM_ON_ORDER_COMPLETION
AFTER
UPDATE ON ORDERS FOR EACH ROW
EXECUTE FUNCTION UPDATE_SUM_ON_ORDER_COMPLETION ();

CREATE OR REPLACE FUNCTION UPDATE_MATERIALS () RETURNS TRIGGER AS $$
BEGIN
    IF (NEW.STATUS = 'Завершен') THEN
		UPDATE MATERIALS
		SET AMOUNT = AMOUNT - MIOT1.AVERAGE_AMOUNT_USED FROM MATERIALS_IN_ORDER_TYPE AS MIOT1
		WHERE NAME IN (
			SELECT MIOT2.MATERIAL_NAME FROM MATERIALS_IN_ORDER_TYPE AS MIOT2
			WHERE MIOT2.ORDER_TYPE_NAME IN (
				SELECT OTIO.NAME FROM ORDER_TYPES_IN_ORDERS AS OTIO
				WHERE OTIO.ID = NEW.ID
			)
		);
		UPDATE MATERIALS
		SET AMOUNT = 0
		WHERE AMOUNT < 0;
	END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE TRIGGER TRIGGER_UPDATE_MATERIALS
AFTER
UPDATE ON ORDERS FOR EACH ROW
EXECUTE FUNCTION UPDATE_MATERIALS ();

CREATE OR REPLACE FUNCTION USER_MONEY_REPLENISHMENT (
	ACCOUNTLOGIN VARCHAR(32),
	REPLENSHMENT_AMOUNT REAL
) RETURNS VOID AS $$
BEGIN
    INSERT INTO TRANSACTIONS (ACCOUNT, TRANSACTION_SUM, WHAT_TRANSACTION, TIMESTAMP)
    VALUES (ACCOUNTLOGIN, REPLENSHMENT_AMOUNT, 'Пополнение', CURRENT_TIMESTAMP);

	UPDATE ACCOUNT
	SET MONEY = MONEY + REPLENSHMENT_AMOUNT
	WHERE LOGIN = ACCOUNTLOGIN;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE OR REPLACE FUNCTION USER_MONEY_DISMISSAL (ACCOUNTLOGIN VARCHAR(32), DISMISSAL_AMOUNT REAL) RETURNS VOID AS $$
BEGIN
    INSERT INTO TRANSACTIONS (ACCOUNT, TRANSACTION_SUM, WHAT_TRANSACTION, TIMESTAMP)
    VALUES (ACCOUNTLOGIN, DISMISSAL_AMOUNT, 'Списание', CURRENT_TIMESTAMP);

	IF (SELECT MONEY - DISMISSAL_AMOUNT FROM ACCOUNT WHERE LOGIN = ACCOUNTLOGIN) < 0 THEN
		INSERT INTO TRANSACTIONS (
        ACCOUNT,
        TRANSACTION_SUM,
        WHAT_TRANSACTION,
		TIMESTAMP) 
		VALUES (
        ACCOUNTLOGIN,
		DISMISSAL_AMOUNT,
        'Отклонено',
		CURRENT_TIMESTAMP);
	ELSE
		UPDATE ACCOUNT
		SET MONEY = MONEY - DISMISSAL_AMOUNT
		WHERE LOGIN = ACCOUNTLOGIN;
	END IF;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE OR REPLACE FUNCTION FINAL_COST (ORDERID INTEGER) RETURNS REAL AS $$
DECLARE
	_COST REAL;
BEGIN
    SELECT SUM(MIOT.AVERAGE_AMOUNT_USED * M.COST) INTO _COST FROM MATERIALS AS M	 				
	JOIN MATERIALS_IN_ORDER_TYPE AS MIOT ON MIOT.MATERIAL_NAME = M.NAME	
	WHERE MIOT.ORDER_TYPE_NAME IN (							
		SELECT NAME FROM ORDER_TYPES_IN_ORDERS 		
		WHERE ID = ORDERID								
	);
	RETURN _COST;
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;

CREATE OR REPLACE FUNCTION GET_ALL_TYPES(ORDERID INTEGER) RETURNS TABLE(type_name VARCHAR(32)) AS $$  
BEGIN
	RETURN QUERY
	SELECT NAME FROM ORDER_TYPE 
	WHERE NAME IN (
		SELECT NAME FROM ORDER_TYPES_IN_ORDERS 
		WHERE ID = ORDERID
	);
END;
$$ LANGUAGE PLPGSQL SECURITY DEFINER;