DROP TABLE MATERIALS_IN_ORDER_TYPE;

DROP TABLE MATERIALS;

DROP TABLE ORDER_TYPES_IN_ORDERS;

DROP TABLE ORDER_TYPE;

DROP TABLE TRANSACTIONS;

DROP TABLE REPORTS;

DROP TABLE MASTER;

DROP TABLE ORDERS;

DROP TABLE ACCOUNT;

DROP TYPE ORDERTYPE;

DROP TYPE ORDERSTATUS;

DROP TYPE USERROLE;

DROP TYPE MEASUREMENTTYPE;

DROP TYPE TRANSACTIONTYPE;

CREATE TYPE ORDERTYPE AS ENUM(
	'Ламинация'
	'Реставрация фото',
	'Колоризация',
	'Ретушь',
	'Восстановление слайдов',
	'Цифровая реставрация',
	'Увеличение фото',
	'Восстановление рамок',
	'Создание коллажей',
	'Реставрация портретов'
);

CREATE TYPE ORDERSTATUS AS ENUM(
	'В обработке',
	'Размещён',
	'Принят мастером',
	'Завершен',
	'Отклонён'
);

CREATE TYPE USERROLE AS ENUM('Пользователь', 'Мастер', 'Администратор');

CREATE TYPE MEASUREMENTTYPE AS ENUM('кг', 'л', 'м', 'шт', 'м в кубе');

CREATE TYPE TRANSACTIONTYPE AS ENUM('Пополнение', 'Списание', 'Отклонено');

CREATE TABLE ACCOUNT (
	LOGIN VARCHAR(32) PRIMARY KEY,
	PASSWORD VARCHAR(32),
	AVATAR_PATH VARCHAR(32),
	FIO VARCHAR(64),
	EMAIL VARCHAR(32),
	PHONE VARCHAR(16),
	MONEY REAL NOT NULL CONSTRAINT POSIBLEMONEY CHECK (MONEY >= 0),
	ROLE USERROLE
);

CREATE TABLE ORDERS (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(32) NOT NULL UNIQUE,
	IMAGE_PATH VARCHAR(32) NOT NULL, 
	CONTRACT_URL VARCHAR(64),
	STATUS ORDERSTATUS,
	CUSTOMER VARCHAR(32) NOT NULL REFERENCES ACCOUNT (LOGIN) ON UPDATE CASCADE,
	MASTER VARCHAR(32) REFERENCES ACCOUNT (LOGIN) ON UPDATE CASCADE
);

CREATE TABLE MASTER (
	LOGIN VARCHAR(32) REFERENCES ACCOUNT (LOGIN) ON UPDATE CASCADE,
	WAGE DECIMAL(5, 4) CONSTRAINT POSIBLEWAGE CHECK (WAGE < 1 AND WAGE > 0),
	EMPLOYMENT_DATE DATE
);

CREATE TABLE REPORTS (
	ID SERIAL PRIMARY KEY,
	REPORTER VARCHAR(32) REFERENCES ACCOUNT (LOGIN) ON UPDATE CASCADE,
	REPORTED VARCHAR(32) REFERENCES ACCOUNT (LOGIN) ON UPDATE CASCADE,
	DESCRIPTION VARCHAR(256)
);

CREATE TABLE TRANSACTIONS(
	ID SERIAL PRIMARY KEY,
	ACCOUNT VARCHAR(32) REFERENCES ACCOUNT (LOGIN) ON UPDATE CASCADE,
	TRANSACTION_SUM REAL NOT NULL,
	WHAT_TRANSACTION TRANSACTIONTYPE,
	TIMESTAMP DATE
);

CREATE TABLE ORDER_TYPE (
	NAME VARCHAR(32) PRIMARY KEY,
	DESCRIPTION VARCHAR(128)
);

CREATE TABLE ORDER_TYPES_IN_ORDERS (
	ID SERIAL REFERENCES ORDERS (ID) ON UPDATE CASCADE,
	NAME VARCHAR(32) REFERENCES ORDER_TYPE (NAME) ON UPDATE CASCADE
);

CREATE TABLE MATERIALS (
	NAME VARCHAR(32) PRIMARY KEY,
	AMOUNT REAL DEFAULT 0,
	COST REAL NOT NULL,
	MEASUREMENT MEASUREMENTTYPE
);

CREATE TABLE MATERIALS_IN_ORDER_TYPE (
	ORDER_TYPE_NAME VARCHAR(32) REFERENCES ORDER_TYPE (NAME) ON UPDATE CASCADE,
	MATERIAL_NAME VARCHAR(32) REFERENCES MATERIALS (NAME) ON UPDATE CASCADE,
	AVERAGE_AMOUNT_USED REAL NOT NULL
);