DROP OWNED BY ACCOUNTED_USER;
DROP ROLE IF EXISTS ACCOUNTED_USER;

DROP OWNED BY WORKER;
DROP ROLE IF EXISTS WORKER;

DROP OWNED BY ADMINISTRATOR;
DROP ROLE IF EXISTS ADMINISTRATOR;

CREATE ROLE ACCOUNTED_USER LOGIN PASSWORD 'QWERTY';
GRANT SELECT ON ORDER_TYPE, MATERIALS, MATERIALS_IN_ORDER_TYPE, MASTER TO ACCOUNTED_USER;
GRANT SELECT, INSERT ON ORDERS, TRANSACTIONS, ORDER_TYPES_IN_ORDERS TO ACCOUNTED_USER;
GRANT SELECT, UPDATE ON ACCOUNT TO ACCOUNTED_USER;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ACCOUNTED_USER;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ACCOUNTED_USER;

CREATE ROLE WORKER LOGIN PASSWORD '09876';
GRANT SELECT ON ORDER_TYPE, MATERIALS, MATERIALS_IN_ORDER_TYPE, MASTER TO WORKER;
GRANT SELECT, INSERT ON TRANSACTIONS, ORDER_TYPES_IN_ORDERS TO WORKER;
GRANT SELECT, UPDATE ON ORDERS, ACCOUNT TO WORKER;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO WORKER;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO WORKER;

CREATE ROLE ADMINISTRATOR LOGIN PASSWORD '12345';
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO ADMINISTRATOR;
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC GRANT ALL ON TABLES TO ADMINISTRATOR;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ADMINISTRATOR;
